name: miscellaneous
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: 2.3.6
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  permission_handler: ^12.0.1
  sensors_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/compass/
