name: miscellaneous
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_compass: ^0.8.1
  flutter_riverpod: ^3.2.0
  geolocator: ^14.0.2
  go_router: ^17.0.0
  google_fonts: ^8.0.0
  google_maps_flutter: ^2.14.0
  google_mobile_ads: ^7.0.0
  local_auth: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  quick_actions: ^1.1.0
  sensors_plus: ^7.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  workmanager: ^0.9.0+3

dev_dependencies:
  build_runner: ^2.11.0
  change_app_package_name: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/compass/
