name: miscellaneous
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.0
  google_fonts: ^8.0.0
  local_auth: ^3.0.0
  permission_handler: ^12.0.1
  sensors_plus: ^7.0.0
  share_plus: ^12.0.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/compass/
